#!/bin/bash

echo "How many files are in the practice directory?"
echo "There are $(find ../../ -type f | wc -l) files in the practice directory"

echo "--------------------------------------------------------------------------"

echo "List every .log file and its size"
find ~/Projects/lab/bash/commands/practice -name "*.log" | xargs du -h

echo "--------------------------------------------------------------------------"
echo "Which scripts inside scripts/ contain the word ERROR?"
result=$(grep "ERROR" ~/Projects/lab/bash/commands/practice/scripts/ -lr)
echo "Answer: $result"

echo "--------------------------------------------------------------------------"
echo "Find the three largest files under practice/"
largest=$(find ~/Projects/lab/bash/commands/practice/ -type f | xargs du -sh | sort -rh | head -3)
echo -e "The largest three files are: \n$largest"

echo "-------------------------------------------------------------------------"
echo "Find all .env and .conf files under configs/"

files=$(find ~/Projects/lab/bash/commands/practice/configs/ -name "*.env" -o -name "*.conf")
echo "$files"

echo "======================================================================================"

echo "How many ERROR lines are in app.log"
echo "$(find ~/Projects/lab/bash/commands/practice/ -name "app.log" | xargs grep ERROR -c)"

echo "===================================================="
echo "Show all 500 status lines from nginx-access.log"
echo "$(find ~/Projects/lab/bash/commands/practice/ -name "nginx-access.log" | xargs grep 500)"

echo "==================================="
echo "Search all log files for the word timeout. Show filenames and line numbers"
echo "$(find ~/Projects/lab/bash/commands/practice/ -type f | xargs grep "timeout" -n)"

echo "====================================="
echo "Find any line across all practice/ mentioning a password, secret or JWT"
grep -Eri "password|secret|JWT"  ~/Projects/lab/bash/commands/practice/

echo "========================================="
echo "Show only lines related to the failed deployment v1.4.0"
find ~/Projects/lab/bash/commands/practice/ -name "deploy.log" | xargs grep v1.4.0

echo "==============================="
echo "Block 3"
echo "-----------------------"

echo "Count requests per IP in nginx-access.log sorted most to least"
find ~/Projects/lab/bash/commands/practice/ -name "nginx-access.log" | xargs cut -d" " -f1 | sort | uniq -c | sort -rn 

echo "----------------------------"
echo "List all unique HTTP status codes in nginx-access.log"
find ~/Projects/lab/bash/commands/practice/ -name "nginx-access.log" | xargs grep -Eo " [0-9]{3} " | tr -d " " | sort -u

echo "============================================="
grep "[ERROR]" ~/Projects/lab/bash/commands/practice/logs/ -r >> /tmp/errors.txt 2> /dev/null 

echo "=============================="
find ~/Projects/lab/bash/commands/practice/ -name "app.log" | xargs cut -d" " -f1 | sort | uniq -c

echo "====================================="
find ~/Projects/lab/bash/commands/practice/ -name "nginx-access.log" | xargs grep -E " [45][0-9]{2} "  

echo "==============================="
echo "Block 4"
echo "==============================="

find ~/Projects/lab/bash/commands/practice" -name "users.tsv" | xargs tail -n +2 | cut -f2

echo "==============================="

find . -name "~/Projects/lab/bash/commands/practice" -name "sales.csv" | tail -n +2 | cut -d"," -f7 | sort | uniq

echo "==============================="

cut -d"=" -f1 app.env | tr [:upper:] [:lower:]

echo "==================================="

tr "," "|" < sales.csv > sales_with_pipes.csv

echo "========================="


