# TODO: Fill this Dockerfile in during Block 6
# Hints:
#   Base image: ubuntu:24.04
#   WORKDIR: /app
#   COPY the greet script
#   RUN chmod +x greet
#   Set ENV defaults for GREETING and NAME
#   CMD to run the script
